version: '3.8'

services:
    APP:
        container_name: APP
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - APP_PORT:80
        depends_on:
            - DB

    DB:
        container_name: DB
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: NAME_DB
            MYSQL_USER: DB_USER
            MYSQL_PASSWORD: DB_PASSWORD
            MYSQL_ROOT_PASSWORD: DB_PASSWORD
        command:  mysqld --sql_mode=""
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - DB_PORT:3306